# Server Config
server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  security:
    user:
      name: livevox
  application:
    name: PhoneBook App
  thymeleaf:
    enabled: true
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phonebookdb?serverTimezone=UTC
    username: root
    password: vertical601

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  path: ${java.io.tmpdir}
  file:
    name: phonebook-challenge.log
    max-size: 5MB
    max-history: 5
  level.org.springframework: info
  level.com.godie: info